// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyCrudApp.Models;

public partial class EmployeeTb
{
    public int Emp_id { get; set; }

    public string Emp_name { get; set; }

    public string Emp_pno { get; set; }

    public decimal? Emp_salary { get; set; }

    public string Emp_gender { get; set; }

    public int? Emp_age { get; set; }

    public string Emp_department { get; set; }

    public string Emp_designation { get; set; }
}