// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MyCrudApp.Models;

public partial class Employee_management_SystemContext : DbContext
{
    public Employee_management_SystemContext()
    {
    }

    public Employee_management_SystemContext(DbContextOptions<Employee_management_SystemContext> options)
        : base(options)
    {
    }

    public virtual DbSet<EmployeeTb> EmployeeTb { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=DESKTOP-DHQ0QJ7\\SQLEXPRESS;Initial Catalog=Employee_management_System;Integrated Security=True;Encrypt=false");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<EmployeeTb>(entity =>
        {
            entity.HasKey(e => e.Emp_id).HasName("PK__Employee__263E2DD338F33224");

            entity.Property(e => e.Emp_department)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Emp_designation)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Emp_gender)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Emp_name)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Emp_pno)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.Emp_salary).HasColumnType("decimal(10, 2)");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}